# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    run_tests(
      scheme: "ScreenshotTest",
      devices: [
        "iPhone 8 Plus",
        "iPhone 13 Pro Max",
        "iPad Pro (12.9-inch) (2nd generation)"
        # "iPad Pro (12.9-inch) (6th generation)" # Doesn't work!
      ]
    )
  end

  desc "Generates localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "ScreenshotTest")
  end

  lane :upload_screenshots do
    upload_to_app_store(
      skip_app_version_update: true,
      skip_binary_upload: true,
      skip_metadata: true
    )
  end
end
